# Generated by Django 4.1.7 on 2023-03-03 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_productoventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoventa',
            name='VENTA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_venta', to='api.venta'),
        ),
    ]
