# Generated by Django 4.1.7 on 2023-04-05 03:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_productoventa_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='CANTIDAD',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
