# Generated by Django 4.1.7 on 2023-04-05 03:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='CORREO',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='DIRECCION',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.direccion'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='TELEFONO',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cliente',
            name='TIPO_PAGO',
            field=models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('CREDITO', 'CREDITO')], max_length=200, null=True),
        ),
    ]
