# Generated by Django 4.1.7 on 2023-04-05 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cliente_correo_cliente_direccion_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='CORREO',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='TELEFONO',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
