# Generated by Django 4.1.7 on 2023-04-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_cliente_contacto_alter_cliente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='IMAGEN',
            field=models.ImageField(default='imagenes/producto_default.png', upload_to='imagenes'),
        ),
    ]
