# Generated by Django 4.1.7 on 2023-04-06 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_producto_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterField(
            model_name='direccion',
            name='COLONIA',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='CP',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='MUNICIPIO',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='IMAGEN',
            field=models.ImageField(default='imagenes/producto_default.jpg', upload_to='imagenes'),
        ),
    ]
