# Generated by Django 4.1.7 on 2023-04-06 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_cliente_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='DESCUENTO',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
