# Generated by Django 4.1.7 on 2023-04-09 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_empleado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='imagen',
            new_name='IMAGEN',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='usuario',
            new_name='USUARIO',
        ),
    ]
