# Generated by Django 4.1.7 on 2023-04-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_imagen_empleado_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='IMAGEN',
            field=models.ImageField(default='imagenes/empleados/user-default.png', upload_to='imagenes/empleados'),
        ),
    ]
