# Generated by Django 4.1.7 on 2023-05-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_empleado_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='CORREO',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
