# Generated by Django 4.1.7 on 2023-05-15 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_cliente_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='CORREO',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='TELEFONO',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
