# Generated by Django 4.1.7 on 2023-05-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_cliente_correo_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='OBSERVACIONES',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
