# Generated by Django 4.1.7 on 2023-05-19 22:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_venta_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='DESCUENTO',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
