# Generated by Django 4.1.7 on 2023-06-04 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_venta_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='DIRECCION',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.direccion'),
        ),
    ]
