# Generated by Django 4.1.7 on 2023-06-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_cliente_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='IMAGEN',
            field=models.ImageField(default='imagenes/productos/producto_default.jpg', upload_to='imagenes/productos'),
        ),
    ]
