# Generated by Django 4.1.7 on 2023-06-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='IMAGEN',
            field=models.ImageField(default='imagenes/default/usuario_default.png', upload_to='imagenes/empleados'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='IMAGEN',
            field=models.ImageField(default='imagenes/default/producto_default.jpg', upload_to='imagenes/productos'),
        ),
    ]
