# Generated by Django 4.1.7 on 2023-09-01 16:56

from django.db import migrations, models


def convert_telefono_to_char(apps, schema_editor):
    Cliente = apps.get_model("api", "Cliente")
    for cliente in Cliente.objects.all():
        cliente.TELEFONO = str(cliente.TELEFONO) if cliente.TELEFONO is not None else ""
        cliente.save()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0033_alter_empleado_usuario"),
    ]

    operations = [
        migrations.RunPython(convert_telefono_to_char),
        migrations.AlterField(
            model_name="cliente",
            name="TELEFONO",
            field=models.CharField(max_length=200, null=True, blank=True),
        ),
    ]
