# Generated by Django 4.1.7 on 2023-09-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20230901_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='TELEFONO',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
