# Generated by Django 4.1.7 on 2023-09-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_direccion_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='OBSERVACIONES',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
