# Generated by Django 4.1.7 on 2023-09-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_cliente_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='OBSERVACIONES',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
