# Generated by Django 4.1.7 on 2023-09-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_venta_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='NOMBRE_CLIENTE',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
