# Generated by Django 4.1.7 on 2023-09-02 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_venta_nombre_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoventa',
            name='PRODUCTO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.producto'),
        ),
    ]
