# Generated by Django 4.1.7 on 2023-09-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_productoventa_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoventa',
            name='NOMBRE_PRODUCTO',
            field=models.CharField(default='', max_length=200),
        ),
    ]
