# Generated by Django 4.1.7 on 2023-09-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='RUTAS',
            field=models.ManyToManyField(to='api.ruta'),
        ),
    ]
