# Generated by Django 4.1.7 on 2023-09-19 19:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_cliente_rutas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='REPARTIDOR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.empleado'),
        ),
        migrations.CreateModel(
            name='SalidaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ATIENDE', models.CharField(max_length=100)),
                ('FECHA', models.DateTimeField(auto_now=True)),
                ('OBSERVACIONES', models.CharField(max_length=200)),
                ('STATUS', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PROGRESO', 'PROGRESO'), ('REALIZADO', 'REALIZADO'), ('CANCELADO', 'CANCELADO')], max_length=100)),
                ('REPARTIDOR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.empleado')),
                ('RUTA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoSalidaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCTO_NOMBRE', models.CharField(max_length=200)),
                ('CANTIDAD_RUTA', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('CANTIDAD_DISPONIBLE', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('STATUS', models.CharField(choices=[('CARGADO', 'CARGADO'), ('VENDIDO', 'VENDIDO'), ('CANCELADO', 'CANCELADO')], max_length=100)),
                ('PRODUCTO_RUTA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
                ('SALIDA_RUTA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salida_ruta_productos', to='api.salidaruta')),
            ],
        ),
        migrations.CreateModel(
            name='DevolucionSalidaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REPARTIDOR', models.CharField(max_length=200)),
                ('ATIENDE', models.CharField(max_length=200)),
                ('ADMINISTRADOR', models.CharField(blank=True, max_length=200)),
                ('PRODUCTO_NOMBRE', models.CharField(max_length=200)),
                ('CATIDAD_DEVOLUCION', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('STATUS', models.CharField(choices=[('REALIZADO', 'REALIZADO'), ('PENDIENTE', 'PENDIENTE')], max_length=200)),
                ('PRODUCTO_DEVOLUCION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
                ('SALIDA_RUTA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salida_ruta_devoluciones', to='api.salidaruta')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteSalidaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLIENTE_NOMBRE', models.CharField(max_length=200)),
                ('STATUS', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('VISITADO', 'VISITADO'), ('CANCELADO', 'CANCELADO')], max_length=100)),
                ('CLIENTE_RUTA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cliente')),
                ('SALIDA_RUTA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salida_ruta_clientes', to='api.salidaruta')),
            ],
        ),
    ]
