# Generated by Django 4.1.7 on 2023-09-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_remove_ruta_repartidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='REPARTIDOR',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
