# Generated by Django 4.1.7 on 2023-09-19 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_ruta_repartidor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='REPARTIDOR',
        ),
    ]
