# Generated by Django 4.1.7 on 2023-09-19 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_remove_ruta_repartidor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidaruta',
            name='RUTA',
        ),
        migrations.AddField(
            model_name='ruta',
            name='REPARTIDOR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.empleado'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='REPARTIDOR_NOMBRE',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
