# Generated by Django 4.1.7 on 2023-09-20 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_cliente_rutas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='DIA',
        ),
        migrations.CreateModel(
            name='RutaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REPARTIDOR_NOMBRE', models.CharField(max_length=200)),
                ('DIA', models.CharField(choices=[('LUNES', 'LUNES'), ('MARTES', 'MARTES'), ('MIERCOLES', 'MIERCOLES'), ('JUEVES', 'JUEVES'), ('VIERNES', 'VIERNES'), ('SABADO', 'SABADO'), ('DOMINGO', 'DOMINGO')], max_length=100)),
                ('REPARTIDOR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.empleado')),
                ('RUTA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ruta')),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='RUTAS',
            field=models.ManyToManyField(blank=True, related_name='clientes_ruta', to='api.rutadia'),
        ),
    ]
