# Generated by Django 4.1.7 on 2023-09-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_remove_ruta_dia_rutadia_alter_cliente_rutas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='NOMBRE',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
