# Generated by Django 4.1.7 on 2023-09-22 20:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_ruta_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidaruta',
            name='REPARTIDOR_NOMBRE',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salidaruta',
            name='RUTA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salida_rutas', to='api.rutadia'),
        ),
        migrations.AddField(
            model_name='salidaruta',
            name='RUTA_NOMBRE',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientesalidaruta',
            name='SALIDA_RUTA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='api.salidaruta'),
        ),
        migrations.AlterField(
            model_name='productosalidaruta',
            name='CANTIDAD_RUTA',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productosalidaruta',
            name='SALIDA_RUTA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='api.salidaruta'),
        ),
        migrations.AlterField(
            model_name='rutadia',
            name='RUTA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_dias', to='api.ruta'),
        ),
        migrations.AlterField(
            model_name='salidaruta',
            name='OBSERVACIONES',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
