# Generated by Django 4.1.7 on 2023-09-24 22:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_salidaruta_repartidor_nombre_salidaruta_ruta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucionsalidaruta',
            name='CATIDAD_DEVOLUCION',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAJERO', models.CharField(max_length=200)),
                ('BODEGA', models.CharField(max_length=200)),
                ('PRODUCTO_NOMBRE', models.CharField(max_length=200)),
                ('CANTIDAD', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('TIPO_AJUSTE', models.CharField(choices=[('FALTANTE', 'FALTANTE'), ('SOBRANTE', 'SOBRANTE')], max_length=10)),
                ('PRODUCTO', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.producto')),
            ],
        ),
    ]
